name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'  # 仅在推送标签时触发

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.4'  # 设置你的 Go 版本

      - name: Build
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o myprogram-${{ matrix.os }}-${{ matrix.arch }} main.go

      - name: Archive binaries
        run: |
          tar -czvf myprogram-${{ matrix.os }}-${{ matrix.arch }}.tar.gz myprogram-${{ matrix.os }}-${{ matrix.arch }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          tag: ${{ github.ref }}
          files: |
            myprogram-linux-amd64.tar.gz
            myprogram-linux-arm64.tar.gz
            myprogram-windows-amd64.tar.gz
            myprogram-darwin-amd64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
